### ISSUE TITLE
Duplicated id's on login page

### ISSUE THREAD

**Issue by SleekPanther** [books4equality/books4equality#50]
Referring to commit "login navbar" 599c47f219474fedd9621946587a34e46e61f8e0 (so that line numbers line up)

on the page   **views/userViews/login.ejs**
Line 91 to line 130
The id's for each field are duplicated.
For instance, the formgroups for **firstName and lastName email** all have **id="signup-email"**

Id's shouldn't be duplicated in html, but i didn't want to mess with them because I didn't know if it would affect the actual signup process.
**Do you think these could be changed to different id's like "*signup-first-name*" or "*signup-password*"**

      	<h4 class="login-header">Create an account</h4>
        
			<div class="form-group">
			  <input type="text" class="form-control signup-field" id="signup-email" name="firstName" placeholder="First name">
			  <label class="login-field-icon fui-triangle-right-large" for="signup-email"></label>
			</div>

        
			<div class="form-group">
			  <input type="text" class="form-control signup-field" id="signup-email" name="lastName" placeholder="Last name">
			  <label class="login-field-icon fui-triangle-right-large" for="signup-email"></label>
			</div>

        
			<div class="form-group">
			  <input type="text" class="form-control signup-field" id="signup-email" name="email" placeholder="Email Address (UVM email only)">
			  <label class="login-field-icon fui-triangle-right-large" for="signup-email"></label>
			</div>

      	
			<div class="form-group">
			  <input type="text" class="form-control signup-field" id="signup-name" type="text" name="username" placeholder="Username"/>
			  <label class="login-field-icon fui-user" for="signup-name"></label>
			</div>

        
			<div class="form-group">
			  <input type="password" class="form-control signup-field" id="signup-password" name="password" value="" placeholder="Password" />
			  <label class="login-field-icon fui-lock" for="signup-pass"></label>
			</div>

        
			<div class="form-group">
			  <input type="password" class="form-control signup-field" id="signup-password-confirm" name="password-confirm" value="" placeholder="Password (confirm)" />
			  <label class="login-field-icon fui-lock" for="signup-pass"></label>
			</div>

        <div>-->

**Comment by Blquinn** [comment]
Okay, fixed.
