### ISSUE TITLE
Press enter to search

### ISSUE THREAD

**Issue by SleekPanther** [books4equality/books4equality#77]
Currently our search button isn't really a "Button", it's an anchor tag
Wondering if we could convert it to an `<input>` Button or Submit button, and then use javascript to click it when the Enter Key is pressed

**Comment by palmerabollo** [comment]
I'd have to try it, but something like this in views/library.ejs should work

```js
$("input.form-control").keyup(function(e) {
    if (e.keyCode == 13) {
        $("#search").click();
    }
});
```

**Comment by Blquinn** [comment]
That worked.

**Comment by SleekPanther** [comment]
@Blquinn you closed this "Press enter to search" issue, but on the live site, it doesn't seem to work. Did you actually implement that feature, or just verify that @palmerabollo 's code works?

**Comment by SleekPanther** [comment]
Blquinn fixed it now
