### ISSUE TITLE
Search fields aren't ignoring trailing spaces

### ISSUE THREAD

**Issue by SleekPanther** [books4equality/books4equality#78]
Type "9780073376332" in the ISBN field and click search
Then try "9780073376332   " with extra spaces or tabs at the end

Result: **No books found**
Same thing happens for leading whitespaces.

**Can JavaScript remove blank spaces from the search query** ***BEFORE*** **it searches the database?**

*Also applies to Title & Category field, not just ISBN*

**Comment by palmerabollo** [comment]
Yes. Can I fix it or is someone already working on it?

**Comment by SleekPanther** [comment]
It would be great if you could fix it. I just noticed the issue, but I imagine it's been like this for a while

**Comment by Blquinn** [comment]
There's probably a lot of sanitation that should be done on many of the forms.

Guido, if you're fixing them, you should know that I just merged a PR, so you should pull before making any changes.

Thanks
